# Generated by Django 6.0 on 2026-08-06 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoLogisticaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('GLOBAL', 'Empresa'), ('OPERACAO', 'Operação'), ('CAMINHAO', 'Caminhão'), ('CARRETA', 'Carreta'), ('DECISAO', 'Decisão')], default='GLOBAL', max_length=12)),
                ('operacao', models.CharField(blank=True, max_length=80)),
                ('caminhao_id', models.PositiveIntegerField(blank=True, null=True)),
                ('carreta_id', models.PositiveIntegerField(blank=True, null=True)),
                ('decisao_referencia', models.CharField(blank=True, max_length=80)),
                ('raio_padrao_busca_km', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('km_vazio_maximo_desejado', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('tempo_espera_maximo_horas', models.DecimalField(decimal_places=2, default=24, max_digits=7)),
                ('margem_minima_desejada', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('custo_medio_hora_parada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_manutencao_por_km', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('custo_pneu_por_km', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('consumo_padrao_vazio', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('consumo_padrao_carregado', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('pesos', models.JSONField(default=dict)),
                ('considerar_pedagio', models.BooleanField(default=True)),
                ('considerar_comissao', models.BooleanField(default=True)),
                ('considerar_custo_hora_parada', models.BooleanField(default=True)),
                ('usar_recomendacoes_ia', models.BooleanField(default=False)),
                ('quantidade_minima_registros_ia', models.PositiveIntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('tipo', models.CharField(choices=[('BASE', 'Base operacional'), ('POLO', 'Polo estratégico')], max_length=8)),
                ('prioridade', models.PositiveSmallIntegerField(default=0)),
                ('probabilidade_manual', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MembroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador'), ('LEITURA', 'Somente leitura')], default='OPERADOR', max_length=16)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='inteligencia_logistica.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_logisticas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(through='inteligencia_logistica.MembroEmpresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ModeloLogisticoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_modelo', models.CharField(max_length=80)),
                ('versao', models.CharField(max_length=40)),
                ('algoritmo', models.CharField(max_length=100)),
                ('periodo_treinamento_inicio', models.DateTimeField(blank=True, null=True)),
                ('periodo_treinamento_fim', models.DateTimeField(blank=True, null=True)),
                ('quantidade_registros', models.PositiveIntegerField(default=0)),
                ('features_utilizadas', models.JSONField(default=list)),
                ('metricas', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('EM_TREINAMENTO', 'Em treinamento'), ('EM_VALIDACAO', 'Em validação'), ('ATIVO', 'Ativo'), ('REPROVADO', 'Reprovado'), ('SUBSTITUIDO', 'Substituído'), ('DESATIVADO', 'Desativado')], default='EM_TREINAMENTO', max_length=20)),
                ('data_treinamento', models.DateTimeField(blank=True, null=True)),
                ('arquivo_modelo', models.CharField(blank=True, max_length=500)),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ParceiroFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('confiabilidade', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OportunidadeFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=120)),
                ('destino', models.CharField(max_length=120)),
                ('tipo_carga', models.CharField(max_length=80)),
                ('tipo_veiculo', models.CharField(blank=True, max_length=80)),
                ('capacidade_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receita', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_vazio', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('tempo_espera_horas', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('probabilidade_continuidade', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('risco_retorno_vazio', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inteligencia_logistica.parceirofrete')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilEstrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('CONSERVADOR', 'Conservador'), ('RENTABILIDADE', 'Rentabilidade'), ('OPERACIONAL', 'Operacional'), ('REDUCAO_VAZIO', 'Redução de vazio'), ('PERSONALIZADO', 'Personalizado')], default='PERSONALIZADO', max_length=24)),
                ('pesos', models.JSONField(default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisaoLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativas', models.JSONField(default=list)),
                ('explicacao', models.JSONField(default=list)),
                ('avisos', models.JSONField(default=list)),
                ('modo', models.CharField(default='REGRAS', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.CharField(blank=True, max_length=24)),
                ('motivo_feedback', models.CharField(blank=True, max_length=160)),
                ('resultado_real', models.JSONField(default=dict)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
                ('oportunidade_escolhida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escolhas', to='inteligencia_logistica.oportunidadefrete')),
                ('oportunidade_recomendada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recomendacoes', to='inteligencia_logistica.oportunidadefrete')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inteligencia_logistica.perfilestrategia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RotaEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carga', models.CharField(blank=True, max_length=80)),
                ('recorrente', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_destino', to='inteligencia_logistica.locallogistico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.empresa')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas_origem', to='inteligencia_logistica.locallogistico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='locallogistico',
            constraint=models.UniqueConstraint(fields=('empresa', 'cidade', 'estado', 'tipo'), name='local_empresa_unico'),
        ),
        migrations.AddConstraint(
            model_name='membroempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario'), name='membro_empresa_unico'),
        ),
        migrations.AddConstraint(
            model_name='modelologisticoia',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_modelo', 'versao'), name='modelo_versao_empresa_unico'),
        ),
    ]
