# Generated by Django 6.0 on 2026-08-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia_logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PracaPedagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodovia', models.CharField(max_length=40)),
                ('praca', models.CharField(max_length=120)),
                ('concessionaria', models.CharField(max_length=160)),
                ('tarifas_por_eixo', models.JSONField(default=dict)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('fonte', models.CharField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('produto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_carga', models.CharField(max_length=80)),
                ('temperatura_controlada', models.BooleanField(default=False)),
                ('granel', models.BooleanField(default=False)),
                ('paletizado', models.BooleanField(default=False)),
                ('ensacado', models.BooleanField(default=False)),
                ('bigbag', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoloLogisticoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('regiao', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nivel_importancia', models.PositiveSmallIntegerField(choices=[(1, 'Regional'), (2, 'Relevante'), (3, 'Estratégico'), (4, 'Nacional')], default=2)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cidade', 'estado'), name='polo_nacional_cidade_uf_unico')],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoPolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('PRODUZ', 'Produz'), ('CONSOME', 'Consome'), ('DISTRIBUI', 'Distribui'), ('INDUSTRIALIZA', 'Industrializa'), ('IMPORTA', 'Importa'), ('EXPORTA', 'Exporta')], default='PRODUZ', max_length=16)),
                ('probabilidade_referencia', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('fonte', models.CharField(blank=True, max_length=300)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.categoriapolo')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='inteligencia_logistica.polologisticonacional')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inteligencia_logistica.produtologistico')),
            ],
        ),
        migrations.AddField(
            model_name='categoriapolo',
            name='polos',
            field=models.ManyToManyField(related_name='categorias', through='inteligencia_logistica.ClassificacaoPolo', to='inteligencia_logistica.polologisticonacional'),
        ),
        migrations.CreateModel(
            name='TipoVeiculoPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(max_length=100)),
                ('tipo_carreta', models.CharField(blank=True, max_length=100)),
                ('eixos_minimos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eixos_maximos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=300)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_permitidos', to='inteligencia_logistica.produtologistico')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_regiao', models.CharField(default='BRASIL', max_length=80)),
                ('destino_regiao', models.CharField(default='BRASIL', max_length=80)),
                ('faixa_distancia', models.CharField(choices=[('CURTA', 'Curta'), ('MEDIA', 'Média'), ('LONGA', 'Longa'), ('GERAL', 'Geral')], max_length=20)),
                ('tipo_veiculo', models.CharField(blank=True, max_length=100)),
                ('faixa_minima_tkm', models.DecimalField(decimal_places=4, max_digits=8)),
                ('faixa_media_tkm', models.DecimalField(decimal_places=4, max_digits=8)),
                ('faixa_maxima_tkm', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ultima_atualizacao', models.DateField()),
                ('fonte', models.CharField(max_length=300)),
                ('nivel_confianca', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_frete', to='inteligencia_logistica.produtologistico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('produto', 'origem_regiao', 'destino_regiao', 'faixa_distancia', 'tipo_veiculo'), name='indicador_frete_unico')],
            },
        ),
        migrations.CreateModel(
            name='FluxoLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('importancia', models.PositiveSmallIntegerField(default=1)),
                ('tipo_fluxo', models.CharField(default='RECORRENTE', max_length=40)),
                ('fonte', models.CharField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_entrada', to='inteligencia_logistica.polologisticonacional')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_saida', to='inteligencia_logistica.polologisticonacional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inteligencia_logistica.produtologistico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('origem', 'destino', 'produto', 'tipo_fluxo'), name='fluxo_logistico_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='classificacaopolo',
            constraint=models.UniqueConstraint(fields=('polo', 'categoria', 'produto', 'papel'), name='classificacao_polo_unica'),
        ),
        migrations.AddConstraint(
            model_name='tipoveiculopermitido',
            constraint=models.UniqueConstraint(fields=('produto', 'tipo_veiculo', 'tipo_carreta'), name='veiculo_produto_unico'),
        ),
    ]
