# Generated by Django 6.0 on 2026-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia_logistica', '0003_carregar_base_nacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaologisticaempresa',
            name='tile_provider',
            field=models.CharField(default='osm', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracaologisticaempresa',
            name='tile_provider_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='oportunidadefrete',
            name='disponibilidade_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oportunidadefrete',
            name='distancia_carregada_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='oportunidadefrete',
            name='fonte_nome',
            field=models.CharField(default='Cadastro manual', max_length=120),
        ),
        migrations.AddField(
            model_name='oportunidadefrete',
            name='fonte_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='oportunidadefrete',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='oportunidadefrete',
            name='verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64, unique=True)),
                ('origem', models.JSONField()),
                ('destino', models.JSONField()),
                ('provider', models.CharField(max_length=40)),
                ('distancia_metros', models.PositiveBigIntegerField()),
                ('tempo_segundos', models.PositiveIntegerField()),
                ('pedagios', models.JSONField(default=list)),
                ('geometria', models.JSONField(default=list)),
                ('resposta', models.JSONField(default=dict)),
                ('data_consulta', models.DateTimeField(auto_now=True)),
                ('valido_ate', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'valido_ate'], name='inteligenci_provide_0fab8b_idx')],
            },
        ),
    ]
