# Generated by Django 6.0 on 2025-12-29 16:53

import despesas.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caminhoes', '0002_remove_caminhao_crlv_cavalo_remove_carreta_crlv'),
        ('motoristas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('IPVA', 'IPVA'), ('SEGURO', 'Seguro'), ('LICENCIAMENTO', 'Licenciamento'), ('RASTREADOR', 'Rastreador'), ('SALARIO', 'Salário Motorista'), ('COMISSAO', 'Comissão Motorista'), ('MANUTENCAO', 'Manutenção'), ('MULTA', 'Multa'), ('GUINCHO', 'Guincho'), ('FRANQUIA_SEGURO', 'Franquia de Seguro'), ('OUTROS', 'Outros')], max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(default='#6366F1', max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_despesa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('OPERACIONAL', 'Custo Operacional'), ('EVENTUAL', 'Despesa Eventual')], default='OPERACIONAL', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor da despesa', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('competencia', models.DateField(default=despesas.models.competencia_padrao, help_text='Mês de referência (formato: YYYY-MM-01)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, help_text='Data de vencimento da despesa', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('caminhao', models.ForeignKey(help_text='Caminhão que recebe este custo', on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='caminhoes.caminhao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='despesas.categoriadespesa')),
                ('motorista', models.ForeignKey(blank=True, help_text='Motorista relacionado (salário/comissão)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='motoristas.motorista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-competencia', '-data_cadastro'],
                'indexes': [models.Index(fields=['usuario', 'caminhao', 'tipo'], name='despesas_de_usuario_927bbc_idx'), models.Index(fields=['categoria', 'status'], name='despesas_de_categor_52cab5_idx'), models.Index(fields=['competencia', 'status'], name='despesas_de_compete_3f68a0_idx')],
            },
        ),
    ]
