# Generated by Django 6.0 on 2025-12-11 13:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caminhoes', '0002_remove_caminhao_crlv_cavalo_remove_carreta_crlv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('IPVA', 'IPVA'), ('SEGURO', 'Seguro'), ('MANUTENCAO', 'Manutenção'), ('ABASTECIMENTO', 'Abastecimento'), ('SALARIO', 'Salário'), ('COMISSAO', 'Comissão'), ('LICENCIAMENTO', 'Licenciamento'), ('PEDAGIO', 'Pedágio'), ('MULTA', 'Multa'), ('OUTROS', 'Outros')], max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(default='#6366F1', max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_despesa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo', models.CharField(choices=[('FIXA', 'Fixa (Parcelada/Diluída)'), ('VARIAVEL', 'Variável'), ('RECORRENTE', 'Recorrente Mensal')], default='VARIAVEL', max_length=20)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('numero_parcela', models.IntegerField(blank=True, null=True)),
                ('total_parcelas', models.IntegerField(default=1)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='despesas/comprovantes/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('caminhao', models.ForeignKey(blank=True, help_text='Caminhão relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='caminhoes.caminhao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='despesas.categoriadespesa')),
                ('despesa_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='despesas.despesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_vencimento', '-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_comissao', models.CharField(choices=[('PERCENTUAL', 'Percentual sobre viagens'), ('FIXA', 'Valor fixo mensal'), ('POR_VIAGEM', 'Por viagem realizada')], default='PERCENTUAL', max_length=20)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_despesa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
