# Generated by Django 6.0 on 2025-12-15 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caminhoes', '0002_remove_caminhao_crlv_cavalo_remove_carreta_crlv'),
        ('despesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionariodespesa',
            old_name='salario_base',
            new_name='salario_mensal',
        ),
        migrations.RemoveField(
            model_name='funcionariodespesa',
            name='tipo_comissao',
        ),
        migrations.RemoveField(
            model_name='funcionariodespesa',
            name='valor_comissao',
        ),
        migrations.AddField(
            model_name='despesa',
            name='ano_referencia',
            field=models.IntegerField(blank=True, help_text='Ano da despesa fixa', null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='mes_referencia',
            field=models.IntegerField(blank=True, help_text='Mês (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='funcionariodespesa',
            name='caminhao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='caminhoes.caminhao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='despesa_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_mensais', to='despesas.despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('FIXA_ANUAL', 'Fixa Anual (Diluída em 12 meses)'), ('FIXA_MENSAL', 'Fixa Mensal (Salário)'), ('VARIAVEL', 'Variável')], default='VARIAVEL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['usuario', 'ano_referencia', 'mes_referencia'], name='despesas_de_usuario_3e2ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['caminhao', 'tipo'], name='despesas_de_caminha_c7ebb0_idx'),
        ),
    ]
