# Generated by Django 6.0 on 2026-01-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caminhoes', '0002_remove_caminhao_crlv_cavalo_remove_carreta_crlv'),
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='caminhao',
            field=models.ForeignKey(blank=True, help_text='Caminhão que recebe este custo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='caminhoes.caminhao'),
        ),
    ]
