# Generated by Django 6.0 on 2026-03-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caminhoes', '0002_remove_caminhao_crlv_cavalo_remove_carreta_crlv'),
        ('despesas', '0002_alter_despesa_caminhao'),
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='caminhao',
            field=models.ForeignKey(blank=True, help_text='Caminhão relacionado (obrigatório exceto para salários/comissões)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='caminhoes.caminhao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='motorista',
            field=models.ForeignKey(blank=True, help_text='Motorista relacionado (obrigatório para salário/comissão)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='motoristas.motorista'),
        ),
    ]
