# Generated by Django 6.0 on 2025-12-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_rename_salario_base_funcionariodespesa_salario_mensal_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='despesa',
            name='despesas_de_usuario_3e2ca2_idx',
        ),
        migrations.RemoveIndex(
            model_name='despesa',
            name='despesas_de_caminha_c7ebb0_idx',
        ),
        migrations.RenameField(
            model_name='funcionariodespesa',
            old_name='salario_mensal',
            new_name='salario_base',
        ),
        migrations.RemoveField(
            model_name='funcionariodespesa',
            name='caminhao',
        ),
        migrations.AddField(
            model_name='funcionariodespesa',
            name='tipo_comissao',
            field=models.CharField(choices=[('PERCENTUAL', 'Percentual sobre viagens'), ('FIXA', 'Valor fixo mensal'), ('POR_VIAGEM', 'Por viagem realizada')], default='PERCENTUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionariodespesa',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='despesa_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='despesas.despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('FIXA', 'Fixa (Parcelada/Diluída)'), ('VARIAVEL', 'Variável'), ('RECORRENTE', 'Recorrente Mensal')], default='VARIAVEL', max_length=20),
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='ano_referencia',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='mes_referencia',
        ),
    ]
