from __future__ import annotations

import unicodedata


class LocalidadeSeguroError(ValueError):
    """Erro base para inconsistências de localização na calculadora."""


class LocalidadeNaoEncontradaError(LocalidadeSeguroError):
    """Origem ou destino não reconhecidos pela camada de normalização."""


class TaxaDeslocamentoNaoEncontradaError(LocalidadeSeguroError):
    """Par de localidades sem taxa cadastrada na matriz convertida da planilha."""


def _remover_acentos(valor: str) -> str:
    normalizado = unicodedata.normalize("NFKD", valor)
    return "".join(caractere for caractere in normalizado if not unicodedata.combining(caractere))


def normalizar_texto_localidade(valor: str) -> str:
    return " ".join(_remover_acentos(valor).strip().lower().split())


LOCALIDADE_LABELS = {
    "acre": "Acre",
    "alagoas": "Alagoas",
    "amapa": "Amapá",
    "amazonas": "Amazonas",
    "bahia": "Bahia",
    "ceara": "Ceará",
    "distrito_federal_brasilia": "D.F.(Brasília)",
    "espirito_santo": "Esp.Santo",
    "goias": "Goiás",
    "maranhao": "Maranhão",
    "mato_grosso": "Mato Grosso",
    "mato_grosso_do_sul": "M. G. do Sul",
    "minas_gerais": "Minas Gerais",
    "para": "Pará",
    "paraiba": "Paraíba",
    "parana": "Paraná",
    "pernambuco": "Pernambuco",
    "piaui": "Piauí",
    "rio_de_janeiro": "Rio de Janeiro",
    "rio_grande_do_norte": "R.G. do Norte",
    "rio_grande_do_sul": "R.G. do Sul",
    "rondonia": "Rondônia",
    "roraima": "Roraima",
    "santa_catarina": "S.Cantarina",
    "sao_paulo": "São Paulo",
    "sergipe": "Sergipe",
    # A planilha recebida usa "Tocantis". Mantemos o identificador para
    # preservar a compatibilidade até a regra de negócio confirmar a grafia.
    "tocantis": "Tocantis",
    "urbano": "Urbano",
}


LOCALIDADE_ALIASES = {
    "acre": "acre",
    "alagoas": "alagoas",
    "amapa": "amapa",
    "amazonas": "amazonas",
    "bahia": "bahia",
    "ceara": "ceara",
    "d.f.(brasilia)": "distrito_federal_brasilia",
    "df(brasilia)": "distrito_federal_brasilia",
    "d.f. brasilia": "distrito_federal_brasilia",
    "distrito federal": "distrito_federal_brasilia",
    "distrito federal brasilia": "distrito_federal_brasilia",
    "brasilia": "distrito_federal_brasilia",
    "esp.santo": "espirito_santo",
    "esp santo": "espirito_santo",
    "esp.santo ": "espirito_santo",
    "espirito santo": "espirito_santo",
    "goias": "goias",
    "maranhao": "maranhao",
    "mato grosso": "mato_grosso",
    "m. g. do sul": "mato_grosso_do_sul",
    "m.g. do sul": "mato_grosso_do_sul",
    "m g do sul": "mato_grosso_do_sul",
    "mato grosso do sul": "mato_grosso_do_sul",
    "minas gerais": "minas_gerais",
    "para": "para",
    "paraiba": "paraiba",
    "parana": "parana",
    "pernambuco": "pernambuco",
    "piaui": "piaui",
    "rio de janeiro": "rio_de_janeiro",
    "r.g. do norte": "rio_grande_do_norte",
    "rg do norte": "rio_grande_do_norte",
    "rio grande do norte": "rio_grande_do_norte",
    "r.g. do sul": "rio_grande_do_sul",
    "rg do sul": "rio_grande_do_sul",
    "rio grande do sul": "rio_grande_do_sul",
    "rondonia": "rondonia",
    "roraima": "roraima",
    "s.cantarina": "santa_catarina",
    "s cantarina": "santa_catarina",
    "santa catarina": "santa_catarina",
    "sao paulo": "sao_paulo",
    "sergipe": "sergipe",
    "tocantis": "tocantis",
    "tocantins": "tocantis",
    "urbano": "urbano",
}


LOCALIDADES_FLUVIAIS = {
    "acre",
    "amazonas",
    "amapa",
    "para",
    "rondonia",
    "roraima",
}


LOCALIDADES_DISPONIVEIS = tuple(LOCALIDADE_LABELS.values())


# Esta estrutura substitui a planilha em produção.
# Os valores abaixo foram extraídos da aba "Tabela Deslocamentos" do arquivo:
# "PLANILHA SEGURO DE CARGAS - CALCULO SEGURO - PIRACEMA.xlsm".
#
# Observação: a primeira célula de cabeçalho ("Para") é apenas um rótulo visual
# da matriz na planilha, não um destino válido de cálculo.
TABELA_DESLOCAMENTOS = {
    "acre": {
        "acre": 0.04,
        "alagoas": 0.3,
        "amapa": 0.26,
        "amazonas": 0.09,
        "bahia": 0.3,
        "ceara": 0.28,
        "distrito_federal_brasilia": 0.18,
        "espirito_santo": 0.26,
        "goias": 0.18,
        "maranhao": 0.28,
        "mato_grosso": 0.12,
        "mato_grosso_do_sul": 0.16,
        "minas_gerais": 0.22,
        "para": 0.24,
        "paraiba": 0.3,
        "parana": 0.24,
        "pernambuco": 0.3,
        "piaui": 0.26,
        "rio_de_janeiro": 0.26,
        "rio_grande_do_norte": 0.3,
        "rio_grande_do_sul": 0.28,
        "rondonia": 0.05,
        "roraima": 0.14,
        "santa_catarina": 0.26,
        "sao_paulo": 0.24,
        "sergipe": 0.3,
        "tocantis": 0.23,
        "urbano": 0.0015,
    },
    "alagoas": {
        "acre": 0.3,
        "alagoas": 0.04,
        "amapa": 0.16,
        "amazonas": 0.3,
        "bahia": 0.06,
        "ceara": 0.07,
        "distrito_federal_brasilia": 0.14,
        "espirito_santo": 0.11,
        "goias": 0.14,
        "maranhao": 0.1,
        "mato_grosso": 0.2,
        "mato_grosso_do_sul": 0.22,
        "minas_gerais": 0.11,
        "para": 0.14,
        "paraiba": 0.05,
        "parana": 0.18,
        "pernambuco": 0.05,
        "piaui": 0.08,
        "rio_de_janeiro": 0.14,
        "rio_grande_do_norte": 0.05,
        "rio_grande_do_sul": 0.22,
        "rondonia": 0.26,
        "roraima": 0.32,
        "santa_catarina": 0.2,
        "sao_paulo": 0.16,
        "sergipe": 0.05,
        "tocantis": 0.12,
        "urbano": 0.0015,
    },
    "amapa": {
        "acre": 0.26,
        "alagoas": 0.16,
        "amapa": 0.08,
        "amazonas": 0.26,
        "bahia": 0.16,
        "ceara": 0.11,
        "distrito_federal_brasilia": 0.14,
        "espirito_santo": 0.22,
        "goias": 0.14,
        "maranhao": 0.09,
        "mato_grosso": 0.2,
        "mato_grosso_do_sul": 0.26,
        "minas_gerais": 0.2,
        "para": 0.09,
        "paraiba": 0.16,
        "parana": 0.22,
        "pernambuco": 0.16,
        "piaui": 0.09,
        "rio_de_janeiro": 0.22,
        "rio_grande_do_norte": 0.16,
        "rio_grande_do_sul": 0.28,
        "rondonia": 0.22,
        "roraima": 0.3,
        "santa_catarina": 0.24,
        "sao_paulo": 0.2,
        "sergipe": 0.16,
        "tocantis": 0.13,
        "urbano": 0.0015,
    },
    "amazonas": {
        "acre": 0.09,
        "alagoas": 0.3,
        "amapa": 0.26,
        "amazonas": 0.08,
        "bahia": 0.3,
        "ceara": 0.28,
        "distrito_federal_brasilia": 0.2,
        "espirito_santo": 0.28,
        "goias": 0.2,
        "maranhao": 0.28,
        "mato_grosso": 0.18,
        "mato_grosso_do_sul": 0.2,
        "minas_gerais": 0.24,
        "para": 0.24,
        "paraiba": 0.3,
        "parana": 0.26,
        "pernambuco": 0.3,
        "piaui": 0.24,
        "rio_de_janeiro": 0.28,
        "rio_grande_do_norte": 0.3,
        "rio_grande_do_sul": 0.3,
        "rondonia": 0.09,
        "roraima": 0.09,
        "santa_catarina": 0.28,
        "sao_paulo": 0.26,
        "sergipe": 0.32,
        "tocantis": 0.2,
        "urbano": 0.0015,
    },
    "bahia": {
        "acre": 0.3,
        "alagoas": 0.06,
        "amapa": 0.16,
        "amazonas": 0.3,
        "bahia": 0.05,
        "ceara": 0.08,
        "distrito_federal_brasilia": 0.14,
        "espirito_santo": 0.08,
        "goias": 0.14,
        "maranhao": 0.1,
        "mato_grosso": 0.16,
        "mato_grosso_do_sul": 0.18,
        "minas_gerais": 0.09,
        "para": 0.12,
        "paraiba": 0.07,
        "parana": 0.14,
        "pernambuco": 0.06,
        "piaui": 0.08,
        "rio_de_janeiro": 0.1,
        "rio_grande_do_norte": 0.08,
        "rio_grande_do_sul": 0.18,
        "rondonia": 0.26,
        "roraima": 0.32,
        "santa_catarina": 0.16,
        "sao_paulo": 0.12,
        "sergipe": 0.06,
        "tocantis": 0.11,
        "urbano": 0.0015,
    },
    "ceara": {
        "acre": 0.28,
        "alagoas": 0.07,
        "amapa": 0.11,
        "amazonas": 0.28,
        "bahia": 0.08,
        "ceara": 0.04,
        "distrito_federal_brasilia": 0.18,
        "espirito_santo": 0.14,
        "goias": 0.18,
        "maranhao": 0.07,
        "mato_grosso": 0.24,
        "mato_grosso_do_sul": 0.24,
        "minas_gerais": 0.16,
        "para": 0.1,
        "paraiba": 0.05,
        "parana": 0.22,
        "pernambuco": 0.06,
        "piaui": 0.07,
        "rio_de_janeiro": 0.18,
        "rio_grande_do_norte": 0.05,
        "rio_grande_do_sul": 0.26,
        "rondonia": 0.26,
        "roraima": 0.32,
        "santa_catarina": 0.24,
        "sao_paulo": 0.2,
        "sergipe": 0.08,
        "tocantis": 0.13,
        "urbano": 0.0015,
    },
    "distrito_federal_brasilia": {
        "acre": 0.18,
        "alagoas": 0.14,
        "amapa": 0.14,
        "amazonas": 0.2,
        "bahia": 0.14,
        "ceara": 0.18,
        "distrito_federal_brasilia": 0.03,
        "espirito_santo": 0.09,
        "goias": 0.05,
        "maranhao": 0.16,
        "mato_grosso": 0.07,
        "mato_grosso_do_sul": 0.08,
        "minas_gerais": 0.06,
        "para": 0.12,
        "paraiba": 0.16,
        "parana": 0.09,
        "pernambuco": 0.16,
        "piaui": 0.18,
        "rio_de_janeiro": 0.09,
        "rio_grande_do_norte": 0.18,
        "rio_grande_do_sul": 0.11,
        "rondonia": 0.14,
        "roraima": 0.26,
        "santa_catarina": 0.09,
        "sao_paulo": 0.06,
        "sergipe": 0.12,
        "tocantis": 0.07,
        "urbano": 0.0015,
    },
    "espirito_santo": {
        "acre": 0.26,
        "alagoas": 0.11,
        "amapa": 0.22,
        "amazonas": 0.28,
        "bahia": 0.08,
        "ceara": 0.14,
        "distrito_federal_brasilia": 0.09,
        "espirito_santo": 0.03,
        "goias": 0.09,
        "maranhao": 0.16,
        "mato_grosso": 0.14,
        "mato_grosso_do_sul": 0.12,
        "minas_gerais": 0.05,
        "para": 0.2,
        "paraiba": 0.12,
        "parana": 0.09,
        "pernambuco": 0.12,
        "piaui": 0.14,
        "rio_de_janeiro": 0.04,
        "rio_grande_do_norte": 0.14,
        "rio_grande_do_sul": 0.12,
        "rondonia": 0.22,
        "roraima": 0.32,
        "santa_catarina": 0.1,
        "sao_paulo": 0.07,
        "sergipe": 0.09,
        "tocantis": 0.14,
        "urbano": 0.0015,
    },
    "goias": {
        "acre": 0.18,
        "alagoas": 0.14,
        "amapa": 0.14,
        "amazonas": 0.2,
        "bahia": 0.14,
        "ceara": 0.18,
        "distrito_federal_brasilia": 0.05,
        "espirito_santo": 0.09,
        "goias": 0.05,
        "maranhao": 0.16,
        "mato_grosso": 0.07,
        "mato_grosso_do_sul": 0.08,
        "minas_gerais": 0.06,
        "para": 0.12,
        "paraiba": 0.16,
        "parana": 0.09,
        "pernambuco": 0.16,
        "piaui": 0.18,
        "rio_de_janeiro": 0.09,
        "rio_grande_do_norte": 0.18,
        "rio_grande_do_sul": 0.11,
        "rondonia": 0.14,
        "roraima": 0.26,
        "santa_catarina": 0.09,
        "sao_paulo": 0.06,
        "sergipe": 0.12,
        "tocantis": 0.08,
        "urbano": 0.0015,
    },
    "maranhao": {
        "acre": 0.28,
        "alagoas": 0.1,
        "amapa": 0.09,
        "amazonas": 0.28,
        "bahia": 0.1,
        "ceara": 0.07,
        "distrito_federal_brasilia": 0.16,
        "espirito_santo": 0.16,
        "goias": 0.16,
        "maranhao": 0.06,
        "mato_grosso": 0.2,
        "mato_grosso_do_sul": 0.24,
        "minas_gerais": 0.16,
        "para": 0.09,
        "paraiba": 0.11,
        "parana": 0.24,
        "pernambuco": 0.1,
        "piaui": 0.07,
        "rio_de_janeiro": 0.2,
        "rio_grande_do_norte": 0.1,
        "rio_grande_do_sul": 0.28,
        "rondonia": 0.24,
        "roraima": 0.32,
        "santa_catarina": 0.26,
        "sao_paulo": 0.2,
        "sergipe": 0.11,
        "tocantis": 0.11,
        "urbano": 0.0015,
    },
    "mato_grosso": {
        "acre": 0.12,
        "alagoas": 0.2,
        "amapa": 0.2,
        "amazonas": 0.18,
        "bahia": 0.16,
        "ceara": 0.24,
        "distrito_federal_brasilia": 0.07,
        "espirito_santo": 0.14,
        "goias": 0.07,
        "maranhao": 0.2,
        "mato_grosso": 0.06,
        "mato_grosso_do_sul": 0.07,
        "minas_gerais": 0.1,
        "para": 0.14,
        "paraiba": 0.22,
        "parana": 0.11,
        "pernambuco": 0.22,
        "piaui": 0.18,
        "rio_de_janeiro": 0.14,
        "rio_grande_do_norte": 0.24,
        "rio_grande_do_sul": 0.16,
        "rondonia": 0.09,
        "roraima": 0.24,
        "santa_catarina": 0.12,
        "sao_paulo": 0.11,
        "sergipe": 0.18,
        "tocantis": 0.1,
        "urbano": 0.0015,
    },
    "mato_grosso_do_sul": {
        "acre": 0.16,
        "alagoas": 0.22,
        "amapa": 0.26,
        "amazonas": 0.2,
        "bahia": 0.18,
        "ceara": 0.24,
        "distrito_federal_brasilia": 0.08,
        "espirito_santo": 0.12,
        "goias": 0.08,
        "maranhao": 0.24,
        "mato_grosso": 0.07,
        "mato_grosso_do_sul": 0.05,
        "minas_gerais": 0.09,
        "para": 0.18,
        "paraiba": 0.24,
        "parana": 0.07,
        "pernambuco": 0.24,
        "piaui": 0.2,
        "rio_de_janeiro": 0.09,
        "rio_grande_do_norte": 0.26,
        "rio_grande_do_sul": 0.11,
        "rondonia": 0.14,
        "roraima": 0.26,
        "santa_catarina": 0.09,
        "sao_paulo": 0.07,
        "sergipe": 0.2,
        "tocantis": 0.14,
        "urbano": 0.0015,
    },
    "minas_gerais": {
        "acre": 0.22,
        "alagoas": 0.11,
        "amapa": 0.2,
        "amazonas": 0.24,
        "bahia": 0.09,
        "ceara": 0.16,
        "distrito_federal_brasilia": 0.06,
        "espirito_santo": 0.05,
        "goias": 0.06,
        "maranhao": 0.16,
        "mato_grosso": 0.1,
        "mato_grosso_do_sul": 0.09,
        "minas_gerais": 0.04,
        "para": 0.18,
        "paraiba": 0.14,
        "parana": 0.07,
        "pernambuco": 0.14,
        "piaui": 0.14,
        "rio_de_janeiro": 0.05,
        "rio_grande_do_norte": 0.14,
        "rio_grande_do_sul": 0.1,
        "rondonia": 0.2,
        "roraima": 0.3,
        "santa_catarina": 0.08,
        "sao_paulo": 0.05,
        "sergipe": 0.1,
        "tocantis": 0.13,
        "urbano": 0.0015,
    },
    "para": {
        "acre": 0.24,
        "alagoas": 0.14,
        "amapa": 0.09,
        "amazonas": 0.24,
        "bahia": 0.12,
        "ceara": 0.1,
        "distrito_federal_brasilia": 0.12,
        "espirito_santo": 0.2,
        "goias": 0.12,
        "maranhao": 0.09,
        "mato_grosso": 0.14,
        "mato_grosso_do_sul": 0.18,
        "minas_gerais": 0.18,
        "para": 0.08,
        "paraiba": 0.14,
        "parana": 0.2,
        "pernambuco": 0.12,
        "piaui": 0.09,
        "rio_de_janeiro": 0.2,
        "rio_grande_do_norte": 0.12,
        "rio_grande_do_sul": 0.26,
        "rondonia": 0.2,
        "roraima": 0.28,
        "santa_catarina": 0.22,
        "sao_paulo": 0.18,
        "sergipe": 0.14,
        "tocantis": 0.12,
        "urbano": 0.0015,
    },
    "paraiba": {
        "acre": 0.3,
        "alagoas": 0.05,
        "amapa": 0.16,
        "amazonas": 0.3,
        "bahia": 0.07,
        "ceara": 0.05,
        "distrito_federal_brasilia": 0.16,
        "espirito_santo": 0.12,
        "goias": 0.16,
        "maranhao": 0.11,
        "mato_grosso": 0.22,
        "mato_grosso_do_sul": 0.24,
        "minas_gerais": 0.14,
        "para": 0.14,
        "paraiba": 0.04,
        "parana": 0.2,
        "pernambuco": 0.05,
        "piaui": 0.08,
        "rio_de_janeiro": 0.16,
        "rio_grande_do_norte": 0.05,
        "rio_grande_do_sul": 0.24,
        "rondonia": 0.28,
        "roraima": 0.32,
        "santa_catarina": 0.22,
        "sao_paulo": 0.18,
        "sergipe": 0.05,
        "tocantis": 0.13,
        "urbano": 0.0015,
    },
    "parana": {
        "acre": 0.24,
        "alagoas": 0.18,
        "amapa": 0.22,
        "amazonas": 0.26,
        "bahia": 0.14,
        "ceara": 0.22,
        "distrito_federal_brasilia": 0.09,
        "espirito_santo": 0.09,
        "goias": 0.09,
        "maranhao": 0.24,
        "mato_grosso": 0.11,
        "mato_grosso_do_sul": 0.07,
        "minas_gerais": 0.07,
        "para": 0.2,
        "paraiba": 0.2,
        "parana": 0.03,
        "pernambuco": 0.2,
        "piaui": 0.2,
        "rio_de_janeiro": 0.06,
        "rio_grande_do_norte": 0.22,
        "rio_grande_do_sul": 0.06,
        "rondonia": 0.2,
        "roraima": 0.3,
        "santa_catarina": 0.04,
        "sao_paulo": 0.04,
        "sergipe": 0.16,
        "tocantis": 0.18,
        "urbano": 0.0015,
    },
    "pernambuco": {
        "acre": 0.3,
        "alagoas": 0.05,
        "amapa": 0.16,
        "amazonas": 0.3,
        "bahia": 0.06,
        "ceara": 0.06,
        "distrito_federal_brasilia": 0.16,
        "espirito_santo": 0.12,
        "goias": 0.16,
        "maranhao": 0.1,
        "mato_grosso": 0.22,
        "mato_grosso_do_sul": 0.24,
        "minas_gerais": 0.14,
        "para": 0.12,
        "paraiba": 0.05,
        "parana": 0.2,
        "pernambuco": 0.04,
        "piaui": 0.08,
        "rio_de_janeiro": 0.16,
        "rio_grande_do_norte": 0.05,
        "rio_grande_do_sul": 0.24,
        "rondonia": 0.26,
        "roraima": 0.32,
        "santa_catarina": 0.24,
        "sao_paulo": 0.16,
        "sergipe": 0.05,
        "tocantis": 0.12,
        "urbano": 0.0015,
    },
    "piaui": {
        "acre": 0.26,
        "alagoas": 0.08,
        "amapa": 0.09,
        "amazonas": 0.24,
        "bahia": 0.08,
        "ceara": 0.07,
        "distrito_federal_brasilia": 0.18,
        "espirito_santo": 0.14,
        "goias": 0.18,
        "maranhao": 0.07,
        "mato_grosso": 0.18,
        "mato_grosso_do_sul": 0.2,
        "minas_gerais": 0.14,
        "para": 0.09,
        "paraiba": 0.08,
        "parana": 0.2,
        "pernambuco": 0.08,
        "piaui": 0.06,
        "rio_de_janeiro": 0.16,
        "rio_grande_do_norte": 0.08,
        "rio_grande_do_sul": 0.24,
        "rondonia": 0.22,
        "roraima": 0.3,
        "santa_catarina": 0.22,
        "sao_paulo": 0.18,
        "sergipe": 0.09,
        "tocantis": 0.1,
        "urbano": 0.0015,
    },
    "rio_de_janeiro": {
        "acre": 0.26,
        "alagoas": 0.14,
        "amapa": 0.22,
        "amazonas": 0.28,
        "bahia": 0.1,
        "ceara": 0.18,
        "distrito_federal_brasilia": 0.09,
        "espirito_santo": 0.04,
        "goias": 0.09,
        "maranhao": 0.2,
        "mato_grosso": 0.14,
        "mato_grosso_do_sul": 0.09,
        "minas_gerais": 0.05,
        "para": 0.2,
        "paraiba": 0.16,
        "parana": 0.06,
        "pernambuco": 0.16,
        "piaui": 0.16,
        "rio_de_janeiro": 0.02,
        "rio_grande_do_norte": 0.18,
        "rio_grande_do_sul": 0.1,
        "rondonia": 0.22,
        "roraima": 0.32,
        "santa_catarina": 0.08,
        "sao_paulo": 0.04,
        "sergipe": 0.12,
        "tocantis": 0.14,
        "urbano": 0.0015,
    },
    "rio_grande_do_norte": {
        "acre": 0.3,
        "alagoas": 0.05,
        "amapa": 0.16,
        "amazonas": 0.3,
        "bahia": 0.08,
        "ceara": 0.05,
        "distrito_federal_brasilia": 0.18,
        "espirito_santo": 0.14,
        "goias": 0.18,
        "maranhao": 0.1,
        "mato_grosso": 0.24,
        "mato_grosso_do_sul": 0.26,
        "minas_gerais": 0.14,
        "para": 0.12,
        "paraiba": 0.05,
        "parana": 0.22,
        "pernambuco": 0.05,
        "piaui": 0.08,
        "rio_de_janeiro": 0.18,
        "rio_grande_do_norte": 0.04,
        "rio_grande_do_sul": 0.26,
        "rondonia": 0.28,
        "roraima": 0.32,
        "santa_catarina": 0.24,
        "sao_paulo": 0.18,
        "sergipe": 0.06,
        "tocantis": 0.13,
        "urbano": 0.0015,
    },
    "rio_grande_do_sul": {
        "acre": 0.28,
        "alagoas": 0.22,
        "amapa": 0.28,
        "amazonas": 0.3,
        "bahia": 0.18,
        "ceara": 0.26,
        "distrito_federal_brasilia": 0.11,
        "espirito_santo": 0.12,
        "goias": 0.11,
        "maranhao": 0.28,
        "mato_grosso": 0.16,
        "mato_grosso_do_sul": 0.11,
        "minas_gerais": 0.1,
        "para": 0.26,
        "paraiba": 0.24,
        "parana": 0.06,
        "pernambuco": 0.24,
        "piaui": 0.24,
        "rio_de_janeiro": 0.1,
        "rio_grande_do_norte": 0.26,
        "rio_grande_do_sul": 0.03,
        "rondonia": 0.24,
        "roraima": 0.32,
        "santa_catarina": 0.04,
        "sao_paulo": 0.07,
        "sergipe": 0.2,
        "tocantis": 0.2,
        "urbano": 0.0015,
    },
    "rondonia": {
        "acre": 0.05,
        "alagoas": 0.26,
        "amapa": 0.22,
        "amazonas": 0.09,
        "bahia": 0.26,
        "ceara": 0.26,
        "distrito_federal_brasilia": 0.14,
        "espirito_santo": 0.22,
        "goias": 0.14,
        "maranhao": 0.24,
        "mato_grosso": 0.09,
        "mato_grosso_do_sul": 0.14,
        "minas_gerais": 0.2,
        "para": 0.2,
        "paraiba": 0.28,
        "parana": 0.2,
        "pernambuco": 0.26,
        "piaui": 0.22,
        "rio_de_janeiro": 0.22,
        "rio_grande_do_norte": 0.28,
        "rio_grande_do_sul": 0.24,
        "rondonia": 0.04,
        "roraima": 0.1,
        "santa_catarina": 0.22,
        "sao_paulo": 0.2,
        "sergipe": 0.28,
        "tocantis": 0.2,
        "urbano": 0.0015,
    },
    "roraima": {
        "acre": 0.14,
        "alagoas": 0.32,
        "amapa": 0.3,
        "amazonas": 0.09,
        "bahia": 0.32,
        "ceara": 0.32,
        "distrito_federal_brasilia": 0.26,
        "espirito_santo": 0.32,
        "goias": 0.26,
        "maranhao": 0.32,
        "mato_grosso": 0.24,
        "mato_grosso_do_sul": 0.26,
        "minas_gerais": 0.3,
        "para": 0.28,
        "paraiba": 0.32,
        "parana": 0.3,
        "pernambuco": 0.32,
        "piaui": 0.3,
        "rio_de_janeiro": 0.32,
        "rio_grande_do_norte": 0.32,
        "rio_grande_do_sul": 0.32,
        "rondonia": 0.1,
        "roraima": 0.08,
        "santa_catarina": 0.32,
        "sao_paulo": 0.3,
        "sergipe": 0.32,
        "tocantis": 0.24,
        "urbano": 0.0015,
    },
    "santa_catarina": {
        "acre": 0.26,
        "alagoas": 0.2,
        "amapa": 0.24,
        "amazonas": 0.28,
        "bahia": 0.16,
        "ceara": 0.24,
        "distrito_federal_brasilia": 0.09,
        "espirito_santo": 0.1,
        "goias": 0.09,
        "maranhao": 0.26,
        "mato_grosso": 0.12,
        "mato_grosso_do_sul": 0.09,
        "minas_gerais": 0.08,
        "para": 0.22,
        "paraiba": 0.22,
        "parana": 0.04,
        "pernambuco": 0.24,
        "piaui": 0.22,
        "rio_de_janeiro": 0.08,
        "rio_grande_do_norte": 0.24,
        "rio_grande_do_sul": 0.04,
        "rondonia": 0.22,
        "roraima": 0.32,
        "santa_catarina": 0.03,
        "sao_paulo": 0.05,
        "sergipe": 0.18,
        "tocantis": 0.18,
        "urbano": 0.0015,
    },
    "sao_paulo": {
        "acre": 0.24,
        "alagoas": 0.16,
        "amapa": 0.2,
        "amazonas": 0.26,
        "bahia": 0.12,
        "ceara": 0.2,
        "distrito_federal_brasilia": 0.06,
        "espirito_santo": 0.07,
        "goias": 0.06,
        "maranhao": 0.2,
        "mato_grosso": 0.11,
        "mato_grosso_do_sul": 0.07,
        "minas_gerais": 0.05,
        "para": 0.18,
        "paraiba": 0.18,
        "parana": 0.04,
        "pernambuco": 0.16,
        "piaui": 0.18,
        "rio_de_janeiro": 0.04,
        "rio_grande_do_norte": 0.18,
        "rio_grande_do_sul": 0.07,
        "rondonia": 0.2,
        "roraima": 0.3,
        "santa_catarina": 0.05,
        "sao_paulo": 0.02,
        "sergipe": 0.14,
        "tocantis": 0.14,
        "urbano": 0.0015,
    },
    "sergipe": {
        "acre": 0.3,
        "alagoas": 0.05,
        "amapa": 0.16,
        "amazonas": 0.32,
        "bahia": 0.06,
        "ceara": 0.08,
        "distrito_federal_brasilia": 0.12,
        "espirito_santo": 0.09,
        "goias": 0.12,
        "maranhao": 0.11,
        "mato_grosso": 0.18,
        "mato_grosso_do_sul": 0.2,
        "minas_gerais": 0.1,
        "para": 0.14,
        "paraiba": 0.05,
        "parana": 0.16,
        "pernambuco": 0.05,
        "piaui": 0.09,
        "rio_de_janeiro": 0.12,
        "rio_grande_do_norte": 0.06,
        "rio_grande_do_sul": 0.2,
        "rondonia": 0.28,
        "roraima": 0.32,
        "santa_catarina": 0.18,
        "sao_paulo": 0.14,
        "sergipe": 0.04,
        "tocantis": 0.11,
        "urbano": 0.0015,
    },
    "tocantis": {
        "acre": 0.23,
        "alagoas": 0.12,
        "amapa": 0.13,
        "amazonas": 0.2,
        "bahia": 0.11,
        "ceara": 0.13,
        "distrito_federal_brasilia": 0.07,
        "espirito_santo": 0.14,
        "goias": 0.08,
        "maranhao": 0.11,
        "mato_grosso": 0.1,
        "mato_grosso_do_sul": 0.14,
        "minas_gerais": 0.13,
        "para": 0.12,
        "paraiba": 0.13,
        "parana": 0.18,
        "pernambuco": 0.12,
        "piaui": 0.1,
        "rio_de_janeiro": 0.14,
        "rio_grande_do_norte": 0.13,
        "rio_grande_do_sul": 0.2,
        "rondonia": 0.2,
        "roraima": 0.24,
        "santa_catarina": 0.18,
        "sao_paulo": 0.14,
        "sergipe": 0.11,
        "tocantis": 0.06,
        "urbano": 0.0015,
    },
    "urbano": {
        "acre": 0.0015,
        "alagoas": 0.0015,
        "amapa": 0.0015,
        "amazonas": 0.0015,
        "bahia": 0.0015,
        "ceara": 0.0015,
        "distrito_federal_brasilia": 0.0015,
        "espirito_santo": 0.0015,
        "goias": 0.0015,
        "maranhao": 0.0015,
        "mato_grosso": 0.0015,
        "mato_grosso_do_sul": 0.0015,
        "minas_gerais": 0.0015,
        "para": 0.0015,
        "paraiba": 0.0015,
        "parana": 0.0015,
        "pernambuco": 0.0015,
        "piaui": 0.0015,
        "rio_de_janeiro": 0.0015,
        "rio_grande_do_norte": 0.0015,
        "rio_grande_do_sul": 0.0015,
        "rondonia": 0.0015,
        "roraima": 0.0015,
        "santa_catarina": 0.0015,
        "sao_paulo": 0.0015,
        "sergipe": 0.0015,
        "tocantis": 0.0015,
        "urbano": 0.0015,
    },
}


def normalizar_localidade(valor: str) -> str:
    chave = normalizar_texto_localidade(valor)
    localidade = LOCALIDADE_ALIASES.get(chave)
    if not localidade:
        opcoes = ", ".join(LOCALIDADES_DISPONIVEIS)
        raise LocalidadeNaoEncontradaError(
            f'Localidade "{valor}" não encontrada. Opções reconhecidas: {opcoes}.'
        )
    return localidade


def obter_label_localidade(chave: str) -> str:
    return LOCALIDADE_LABELS[chave]


def localidade_tem_taxa_fluvial(origem: str, destino: str) -> bool:
    return origem in LOCALIDADES_FLUVIAIS or destino in LOCALIDADES_FLUVIAIS


def buscar_taxa_deslocamento(origem: str, destino: str) -> tuple[float, str, str, str]:
    origem_canonica = normalizar_localidade(origem)
    destino_canonico = normalizar_localidade(destino)

    taxa = TABELA_DESLOCAMENTOS.get(origem_canonica, {}).get(destino_canonico)
    if taxa is not None:
        return taxa, "origem-destino", origem_canonica, destino_canonico

    taxa_invertida = TABELA_DESLOCAMENTOS.get(destino_canonico, {}).get(origem_canonica)
    if taxa_invertida is not None:
        return taxa_invertida, "destino-origem", origem_canonica, destino_canonico

    raise TaxaDeslocamentoNaoEncontradaError(
        "Taxa de deslocamento não cadastrada para a combinação informada. "
        "Preencha a matriz TABELA_DESLOCAMENTOS com os valores extraídos da planilha."
    )
