# Generated by Django 6.0 on 2025-12-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conjunto', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_cavalo', models.CharField(blank=True, max_length=10, null=True)),
                ('renavam_cavalo', models.CharField(blank=True, max_length=20, null=True)),
                ('marca_modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('crlv_cavalo', models.FileField(blank=True, null=True, upload_to='crlv/')),
                ('qtd_placas', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caminhoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('renavam', models.CharField(blank=True, max_length=20, null=True)),
                ('crlv', models.FileField(blank=True, null=True, upload_to='crlv/')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carretas', to='caminhoes.caminhao')),
            ],
        ),
    ]
