# Generated by Django 6.0 on 2025-12-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conjunto', models.CharField(max_length=100)),
                ('placa_cavalo', models.CharField(max_length=10)),
                ('crlv_cavalo', models.FileField(blank=True, null=True, upload_to='crlv/')),
                ('qtd_placas', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('crlv', models.FileField(blank=True, null=True, upload_to='crlv/')),
                ('caminhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carretas', to='caminhoes.caminhao')),
            ],
        ),
    ]
