# Generated by Django 6.0 on 2025-12-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caminhoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caminhao',
            name='crlv_cavalo',
        ),
        migrations.RemoveField(
            model_name='carreta',
            name='crlv',
        ),
    ]
