# Generated by Django 6.0 on 2025-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caminhoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhao',
            name='nome_conjunto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caminhao',
            name='placa_cavalo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carreta',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
