# Generated by Django 6.0 on 2025-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caminhoes', '0002_alter_caminhao_nome_conjunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminhao',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caminhao',
            name='renavam_cavalo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carreta',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
