# Generated by Django 6.0 on 2025-12-29 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motoristas', '0001_initial'),
        ('viagens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('total_viagens', models.IntegerField()),
                ('valor_total_viagens', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_vales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_a_receber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoristas.motorista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='ItemAcerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_tonelada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField()),
                ('acerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='acertos.acerto')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagens.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='ValeAcerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='acertos.acerto')),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoristas.vale')),
            ],
        ),
    ]
