# Generated by Django 6.0 on 2026-04-17 13:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acertos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acerto',
            name='desconto_fixo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='acerto',
            name='desconto_vales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='acerto',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='RegraAcerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('aplicar_vales_pendentes', models.BooleanField(default=True)),
                ('desconto_fixo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_acerto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ativo', '-data_atualizacao'],
            },
        ),
        migrations.AddField(
            model_name='acerto',
            name='regra_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acertos', to='acertos.regraacerto'),
        ),
    ]
